version: '2'
services:
  plex_host:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Boise
      - PLEX_CLAIM=claim-9ZxPdxZP1skVTWXaU44z
    network_mode: host
    volumes:
      - /Volumes/Repositories/Plex/database
      - /Volumes/Repositories/Plex/transcode
      - /Volumes/Repositories/Plex/media
  plex_bridge:
      container_name: plex
      image: plexinc/pms-docker
      restart: unless-stopped
      ports:
        - 32400:32400/tcp
        - 3005:3005/tcp
        - 8324:8324/tcp
        - 32469:32469/tcp
        - 1900:1900/udp
        - 32410:32410/udp
        - 32412:32412/udp
        - 32413:32413/udp
        - 32414:32414/udp
      environment:
        - TZ=America/Boise
        - PLEX_CLAIM=claim-MqpWJhtkvUBSDykPWyGK
        - ADVERTISE_IP=http://45.56.55.146:32400/
      hostname: raspberrypi
      volumes:
        - /Volumes/Repositories/Plex/database
        - /Volumes/Repositories/Plex/transcode
        - /Volumes/Repositories/Plex/media
